apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
  - name: goserver-service
    port: 80 # Porta do Service
    targetPort: 8000 # Porta do Container. Onde a aplicacao esta rodando
    protocol: TCP
    # nodePort: 30001 # entre 30000 e 32767 --> Usado somente no NodePort
      
